name: Print Txt file



on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'Chose your Server'
        required: true
        type: choice
        default: 'staging'

        options:
          - staging
          - production

env:
  ROY: "Hello World !"


jobs:
  print_txt_file:
    runs-on: ubuntu-latest

    env:
      ROY_ENV: ${{ secrets.ROY_ENV }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print The ROY_ENV Variable
        run: |
          echo "The env variable ROY_ENV is: $ROY_ENV"

      - name: Print the MY_VAR variable
        run: |
          echo "The env variable MY_VAR is: $MY_VAR"
      - name: Print The Env Variable Data
        run: |
          echo "The env variable ROY is: ${{vars.MY_VAR}}"

      - name: Print User inputs
        run: |
          echo "User input: '${{ github.event.inputs.example_input }}'"
    
      - name: Check The user input
        run: |
          if [ "${{ github.event.inputs.example_input }}" = "staging" ]; then
            echo "You chose staging server"
          elif [ "${{ github.event.inputs.example_input }}" = "production" ]; then
            echo "You chose production server"
          else
            echo "Invalid input"
            exit 1
          fi


      - name: Print contents of txt file
        run: |
          cat roy.txt
           
      
 






